[package]
name = "cmdr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.14", features = [ "macros", "process", "fs", "io-util", "io-std", "rt-multi-thread" ] }